### ISSUE TITLE
docker运行权限问题

### ISSUE THREAD

**Issue by insomnia417** [xhongc/music-tag-web#119]
可以添加UID,GID,UMASK控制变量吗？
运行环境：unraid 6.12.4
docker默认运行在root权限下，整理文件以后，文件权限是0755，
强制固定--user 99:100 ，但是权限组还是0755

**Comment by shanyan-wcx** [comment]
+1

**Comment by xtay573269555** [comment]
+1
希望支持 `-e PUID=1000 -e PGID=1000` 或者 `--user 1000:1000`

**Comment by djdjfjfkeocj** [comment]
yes!!!!请尽快支持！！！！please!!!!!

**Comment by da1234cao** [comment]
@xhongc ，请问下。关闭这个issue，是这个issue已解决，还是目前不支持这个issue的功能? 😄

**Comment by xhongc** [comment]
> @xhongc ，请问下。关闭这个issue，是这个issue已解决，还是目前不支持这个issue的功能? 😄

支持了

**Comment by da1234cao** [comment]
> > @xhongc ，请问下。关闭这个issue，是这个issue已解决，还是目前不支持这个issue的功能? 😄
> 
> 支持了

我尝试了最新的镜像，似乎还是会报错。

```shell
root@vultr /h/d/s/music-tag-web# whoami 
root
root@vultr /h/d/s/music-tag-web# pwd
/home/da1234cao/software/music-tag-web


root@vultr /h/d/s/music-tag-web# cat docker-compose.yml 
version: '3'

services:
  music-tag:
    user: "1001:1001"
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8002:8002"
    volumes:
      - /home/da1234cao/Sync/music:/app/media
      - /home/da1234cao/software/music-tag-web/config:/app/data 
    restart: always

root@vultr /h/d/s/music-tag-web# docker-compose up
Starting music-tag-web ... done
Attaching to music-tag-web
music-tag-web | useradd: Permission denied.
music-tag-web | useradd: cannot lock /etc/passwd; try again later.
music-tag-web | user musictag not exists, create it
music-tag-web | usermod: user 'musictag' does not exist
music-tag-web | groupmod: group 'musictag' does not exist
music-tag-web | chown: invalid user: ‘musictag:musictag’
music-tag-web | chmod: changing permissions of '/app/supervisor.conf': Operation not permitted
music-tag-web | error: failed switching to "musictag": unable to find user musictag: no matching entries in passwd file

root@vultr /h/d/s/music-tag-web# ls -alh /home/da1234cao/Sync/music
total 24K
drwxr----- 6 da1234cao da1234cao 4.0K Jun  6 10:26 ./
drwxr-xr-x 4 da1234cao da1234cao 4.0K Jun  6 10:26 ../
drwxr----- 5 da1234cao da1234cao 4.0K Jul  3 05:13 中文歌曲/
drwxr----- 2 da1234cao da1234cao 4.0K Jun  6 10:26 日文歌曲/
drwxr----- 3 da1234cao da1234cao 4.0K Jun  6 10:26 纯音乐/
drwxr----- 2 da1234cao da1234cao 4.0K Jun  6 10:26 英文歌曲/

root@vultr /h/d/s/music-tag-web# ls -alh /home/da1234cao/software/music-tag-web/config
total 8.0K
drwxr-xr-x 2 da1234cao da1234cao 4.0K Jun  6 14:56 ./
drwxr-xr-x 3 da1234cao da1234cao 4.0K Jun  6 15:02 ../
```

**Comment by hack2012** [comment]
为什么使用群晖yml部署以后，不显示音乐了，看docker日志提示权限拒绝？
![1](https://github.com/user-attachments/assets/f2fc9867-a78b-4072-87a9-ab361511babb)

**Comment by hack2012** [comment]
解决了，默认运行参数会把PUID和PGID设置为1000，把这2个参数去掉就行了。

**Comment by NewHanly** [comment]
> > > @xhongc ，请问下。关闭这个issue，是这个issue已解决，还是目前不支持这个issue的功能? 😄
> > 
> > 
> > 支持了
> 
> 我尝试了最新的镜像，似乎还是会报错。

docker-composed的话不是使用user: 1001:1001,要用environment
```
services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8002:8002"
    volumes:
      - /home/da1234cao/Sync/music:/app/media
      - /home/da1234cao/software/music-tag-web/config:/app/data 
    environment:
      - PUID=1001
      - PGID=1001
    restart: always
```
